FROM node:14

WORKDIR /app

COPY /pipelined.app/package*.json ./

RUN npm config set registry https://registry.npmjs.org/
ENV PATH="/root/.meteor:$PATH"
RUN curl https://install.meteor.com/ | sh
RUN export PATH=/root/.meteor:$PATH

# RUN npm install

COPY /pipelined.app/ ./

ENV PORT=80

EXPOSE 80

CMD ["meteor", "run", "--allow-superuser"]